name: tripzz
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  flutter_iconly: ^1.0.2
  flutter_svg: ^1.1.6
  hooks_riverpod: ^2.1.1
  go_router: ^5.1.5
  flutter_native_splash: ^2.2.13
  heroicons: ^0.7.0
  flutter_screenutil: ^5.6.0
  salomon_bottom_bar: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/svg/

flutter_native_splash:
  color: "#f6f9fa"
  image: assets/img/splash_logo.png
